### ISSUE TITLE
Creating `dbt_cloud_databricks_credential` fails

### ISSUE THREAD

**Issue by lassebenni** [GtheSheep/terraform-provider-dbt-cloud#136]
Hi,

I am getting  `The request was invalid. Please double check the provided data and try again`:
```
╷
│ Error: POST url: https://cloud.getdbt.com/api/v3/accounts/x/projects/x/credentials/x/, status: 400, body: {"status":{"code":400,"is_success":false,"user_message":"The request was invalid. Please double check the provided data and try again.","developer_message":""},"data":{"credential_details":"{'fields': None, 'field_order': None} is not valid under any of the given schemas"}}
│ 
│   with dbt_cloud_databricks_credential.databricks,
│   on main.tf line 52, in resource "dbt_cloud_databricks_credential" "databricks":
│   52: resource "dbt_cloud_databricks_credential" "databricks" {
```

when trying to create

```

resource "dbt_cloud_databricks_credential" "databricks" {
  project_id  = local.project_id
  adapter_id  = dbt_cloud_connection.databricks.adapter_id
  num_threads = 16
  target_name = "default"
  token       = "<my-databricks-token>"
}

```

Seems that the post endpoint does not like the data being sent? I tried to look at the API docs in https://docs.getdbt.com/dbt-cloud/api-v2 but couldn't find the right endpoint to create credentials.. Not sure how to proceed.

**Comment by b-per** [comment]
Which version of the provider are you using?

The [doc for the endpoint](https://documenter.getpostman.com/view/14183654/UyxohieD#d0d7c003-05b0-4e0c-88ce-354c36293444) is stored on the page with the different v3 endpoints.

**Comment by grindheim** [comment]
We also get the same error message, using provider:
```
dbt = {
      source = "GtheSheep/dbt-cloud"
      version = "0.1.9"
    }
```
The error message references version `v3`
```
│ Error: POST url: https://cloud.getdbt.com/api/v3/accounts/x/projects/x/credentials/x/, status: 400, body: {"status":{"code":400,"is_success":false,"user_message":"The request was invalid. Please double check the provided data and try again.","developer_message":""},"data":{"credential_details":"{'fields': None, 'field_order': None} is not valid under any of the given schemas"}}
│ 
│   with dbt_cloud_databricks_credential.databricks_credential,
│   on dbt_cloud_environment.tf line 9, in resource "dbt_cloud_databricks_credential" "databricks_credential":
│    9: resource "dbt_cloud_databricks_credential" "databricks_credential" {
```
According to the doc for the endpoint,  rather than None, None, the credential details should have had the following format:
![image](https://github.com/GtheSheep/terraform-provider-dbt-cloud/assets/19465110/6fdee9cd-63bd-4997-a9fe-f24165f1496b)

**Comment by b-per** [comment]
I will try to reproduce it if more people have the same issue

**Comment by b-per** [comment]
I could reproduce the issue. 

While not being too complex the fix is not a one liner either so it might take me a couple of days to get it all working and making sure that we are not breaking anything else along the way.

The complexity with Databricks is that different dbt adapters support different parameters (e.g. `catalog` working with `dbt-databricks` but not `dbt-spark`)
